import assert from 'node:assert/strict';
import { access } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const root = await import('../../dist/index.js');
const messages = await import('../../dist/messages/index.js');
const stream = await import('../../dist/stream/index.js');
const nodeTransport = await import('sip-worker/transport/node');
const browserTransport = await import('sip-worker/transport/browser');
const required = require('../../dist/index.cjs');
const requiredNodeTransport = require('sip-worker/transport/node');
const requiredBrowserTransport = require('sip-worker/transport/browser');
assert.equal(typeof root.SipStreamDecoder, 'function');
assert.equal(typeof root.SipIngress, 'function');
assert.equal(typeof stream.SipStreamDecoder, 'function');
assert.equal(typeof messages.parseMessage, 'function');
assert.equal(typeof required.serializeMessage, 'function');
assert.equal(typeof nodeTransport.NodeUdpTransport, 'function');
assert.equal(typeof nodeTransport.NodeTcpTransport, 'function');
assert.equal(typeof nodeTransport.NodeWebSocketTransport, 'function');
assert.equal(typeof browserTransport.BrowserWebSocketTransport, 'function');
assert.equal(typeof requiredNodeTransport.NodeUdpTransport, 'function');
assert.equal(typeof requiredNodeTransport.NodeTcpTransport, 'function');
assert.equal(typeof requiredNodeTransport.NodeWebSocketTransport, 'function');
assert.equal(typeof requiredBrowserTransport.BrowserWebSocketTransport, 'function');
await access(new URL('../../dist/transport/node/index.d.ts', import.meta.url));
await access(new URL('../../dist/transport/browser/index.d.ts', import.meta.url));
